/*
 * This source file was generated by the Gradle 'init' task
 */
package org.perhitungannilaiakhir;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class PerhitunganNilaiAkhirTest {
    @Test void perhitunganNilaiAkhirIsValid() {
        assertEquals(PerhitunganNilaiAkhir.hitungNilaiAkhir(80, 80, 85), 82.0);
    }

    @Test void perhitunganNilaiAkhirIsInvalid() {
        assertNotEquals(PerhitunganNilaiAkhir.hitungNilaiAkhir(80, 80, 85), 80.0);
    }
}
