/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import org.validasidata.ValidasiData;
import org.perhitungannilaiakhir.PerhitunganNilaiAkhir;
import java.util.Scanner;

public class App {
    private static double nilaiTugas;
    private static double nilaiUts;
    private static double nilaiUas;
    private static double nilaiAkhir;
    private static boolean selesai = false;
    private static Scanner scanner = new Scanner(System.in);

    public static void main(String[] args) {
        boolean valid = false;

        while (!selesai) {
            try {
                System.out.print("Masukkan Nilai Tugas (0-100)  : ");
                nilaiTugas = Double.parseDouble(scanner.nextLine().trim());

                System.out.print("Masukkan Nilai UTS (0-100)    : ");
                nilaiUts = Double.parseDouble(scanner.nextLine().trim());

                System.out.print("Masukkan Nilai UAS (0-100)    : ");
                nilaiUas = Double.parseDouble(scanner.nextLine().trim());

                // Validasi menggunakan modul ValidasiData
                valid = ValidasiData.validasi(nilaiTugas, nilaiUts, nilaiUas);

                if (!valid) {
                    System.out.println("\n[ERROR] Data tidak valid! Pastikan:");
                    System.out.println("  - Semua nilai berada dalam rentang 0-100");
                    System.out.println("  - Tidak semua nilai bernilai 0");
                    System.out.println("Silakan input ulang.\n");
                }else{
                    System.out.println("\nData valid! Nilai Tugas: " + nilaiTugas + ", Nilai UTS: " + nilaiUts + ", Nilai UAS: " + nilaiUas + "\n");
                    
                    // Menghitung nilai akhir jika data valid
                    nilaiAkhir = PerhitunganNilaiAkhir.hitungNilaiAkhir(nilaiTugas, nilaiUts, nilaiUas);
                    System.out.println("Nilai Akhir: " + nilaiAkhir);
                }

                System.out.print("Selesai: (ya/tidak)?");
                selesai = scanner.nextLine().trim().equalsIgnoreCase("ya");
                if (selesai) {
                    System.out.println("Program selesai. Terima kasih!");
                    break;
                }
            } catch (NumberFormatException e) {
                System.out.println("\n[ERROR] Input harus berupa angka! Silakan input ulang.\n");
            }
        }
    }
}

