/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Scanner;

public class App {
    private final Scanner scanner;
    private final PengolahanNilaiMahasiswa pengolahanNilaiMahasiswa;

    public App(
            Scanner scanner,
            PengolahanNilaiMahasiswa pengolahanNilaiMahasiswa) {
        this.scanner = scanner;
        this.pengolahanNilaiMahasiswa = pengolahanNilaiMahasiswa;
    }

    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        App app = new App(scanner, new PengolahanNilaiMahasiswa());
        app.jalankan();
    }

    public void jalankan() {
        boolean berjalan = true;

        while (berjalan) {
            tampilkanMenu();
            String pilihan = scanner.nextLine().trim();

            switch (pilihan) {
                case "1" -> prosesInputNilai();
                case "0" -> berjalan = false;
                default -> System.out.println("\n[ERROR] Pilihan menu tidak tersedia.\n");
            }
        }

        System.out.println("Program selesai. Terima kasih!");
    }

    private void tampilkanMenu() {
        System.out.println("=== MENU PENGOLAHAN NILAI MAHASISWA ===");
        System.out.println("1. Input dan proses nilai mahasiswa");
        System.out.println("0. Keluar");
        System.out.print("Pilih menu: ");
    }

    private void prosesInputNilai() {
        boolean selesaiInputValid = false;

        while (!selesaiInputValid) {
            try {
                PengolahanNilaiMahasiswa.Mahasiswa mahasiswa = pengolahanNilaiMahasiswa.mintaInput(scanner);
                PengolahanNilaiMahasiswa.HasilPengolahan hasil = pengolahanNilaiMahasiswa.proses(mahasiswa);

                tampilkanHasil(mahasiswa, hasil);
                selesaiInputValid = true;
            } catch (NumberFormatException e) {
                System.out.println("\n[ERROR] Input harus berupa angka. Silakan input ulang.\n");
            } catch (IllegalArgumentException | IllegalStateException e) {
                System.out.println("\n[ERROR] " + e.getMessage() + "\n");
            }
        }
    }

    private void tampilkanHasil(
            PengolahanNilaiMahasiswa.Mahasiswa mahasiswa,
            PengolahanNilaiMahasiswa.HasilPengolahan hasil) {
        System.out.println("\n=== HASIL PENGOLAHAN NILAI ===");
        System.out.println("Nama Mahasiswa  : " + mahasiswa.nama());
        System.out.println("Nilai Tugas     : " + mahasiswa.nilaiTugas());
        System.out.println("Nilai UTS       : " + mahasiswa.nilaiUts());
        System.out.println("Nilai UAS       : " + mahasiswa.nilaiUas());
        System.out.println("Nilai Akhir     : " + hasil.nilaiAkhir());
        System.out.println("Grade           : " + hasil.grade());
        System.out.println("Status Kelulusan: " + hasil.statusKelulusan());
        System.out.println();
    }
}
