/*
 * This source file was generated by the Gradle 'init' task
 */
package org.penentuangrade;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class PenentuanGradeTest {
    @Test void testGradeA() {
        // Test kasus untuk nilai A
        assertEquals('A', PenentuanGrade.penentuanGrade(90.0));    
    }
    @Test void testGradeB() {
        // Test kasus untuk nilai B
        assertEquals('B', PenentuanGrade.penentuanGrade(80.0));
    }

    @Test void testGradeC() {
        // Test kasus untuk nilai C
        assertEquals('C', PenentuanGrade.penentuanGrade(60.0));
    }
    
    @Test void testGradeD() {
        // Test kasus untuk nilai D
        assertEquals('D', PenentuanGrade.penentuanGrade(59.0));
    }
    @Test void testGradeE() {
        // Test kasus untuk nilai E
        assertEquals('E', PenentuanGrade.penentuanGrade(49.0));
    }

}
