/*
 * This source file was generated by the Gradle 'init' task
 */
package org.penentuankelulusan;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class PenentuanKelulusanTest {
    @Test void testKelulusanLulus() {
        assertEquals(true, PenentuanKelulusan.penentuanKelulusan(60.0));
    }

    @Test void testKelulusanTidakLulus() {
        assertEquals(false, PenentuanKelulusan.penentuanKelulusan(59.0));
    }
}
