/*
 * This source file was generated by the Gradle 'init' task
 */
package org.penentuankelulusan;

public class PenentuanKelulusan {
    public static boolean penentuanKelulusan(double nilai_akhir) {
        // Validasi: Semua nilai harus antara 0 dan 100, dan tidak semua boleh 0
        if (nilai_akhir >= 60) {
            return true;
        }else {
            return false;
        }
    }
}
