/*
 * This source file was generated by the Gradle 'init' task
 */
package org.perhitungannilaiakhir;

public class PerhitunganNilaiAkhir {
    public static double hitungNilaiAkhir(double nilaiTugas, double nilaiUts, double nilaiUas) {
        return (0.3 * nilaiTugas) + (0.3 * nilaiUts) + (0.4 * nilaiUas);
    }
}