/*
 * This source file was generated by the Gradle 'init' task
 */
package org.validasidata;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ValidasiDataTest {
    @Test void validasiDataIsValid() {
        assertEquals(ValidasiData.validasi(80, 80, 85), true);
    }

    @Test void validasiDataIsInvalid() {
        assertEquals(ValidasiData.validasi(80, 120, 85), false);
        
    }
}
