/*
 * This source file was generated by the Gradle 'init' task
 */
package org.validasidata;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ValidasiDataTest {
    @Test void validasiDataHasCorrectValue() {
        Integer result = ValidasiData.test();
        assertEquals(42, result, "ValidasiData.test() should return 42");
    }
}
