/*
 * This source file was generated by the Gradle 'init' task
 */
package org.validasidata;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ValidasiDataTest {
    @Test void validasiDataIsValid() {
        assertEquals(ValidasiData.validasi(80, 80, 85), true);
    }

    @Test void validasiDataBatasBawah() {
        assertEquals(ValidasiData.validasi(0, 0, 0), false);
    }

    @Test void validasiDataBatasAtas() {
        assertEquals(ValidasiData.validasi(120, 80, 85), false);
    }
}
