/*
 * This source file was generated by the Gradle 'init' task
 */
package org.penentuangrade;

public class PenentuanGrade {
    public static char penentuanGrade(double nilaiAkhir) {
        if (nilaiAkhir >= 85) {
            return 'A';
        } else if (nilaiAkhir >= 70) {
            return 'B';
        } else if (nilaiAkhir >= 60) {
            return 'C';
        } else if (nilaiAkhir >= 50) {
            return 'D';
        } else {
            return 'E';
        }
    }
}

